BOOK_CATEGORY_CHOICES = (
    ("art", "Art"),
    ("arc", "Architecture"),
    ("aut", "Autobiography"),
    ("bus", "Business/economics"),
    ("chi", "Children's"),
    ("fic", "Fiction"),
    ("hea", "Health/fitness"),
    ("his", "History"),
    ("nov", "Novel"),
    ("jou", "Journal"),
    ("poe", "Poetry"),
    ("rel", "Religion/spirituality"),
    ("sci", "Science"),
    ("spo", "Sports_and_leisure"),
    ("tex", "Textbook"),
    ("tra", "Travel"),
)
