# Generated by Django 3.0.8 on 2020-11-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomId', models.CharField(default='0', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Chatkit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokenProvider', models.CharField(default='0', max_length=120)),
                ('instanceLocator', models.CharField(default='0', max_length=100)),
            ],
        ),
    ]
