# Generated by Django 3.0.8 on 2020-11-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FollowBridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.PositiveIntegerField()),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('bio', models.CharField(blank=True, max_length=500, null=True)),
                ('website', models.URLField(blank=True)),
                ('points', models.IntegerField(default=0)),
                ('occupation', models.CharField(max_length=100)),
                ('pic', models.ImageField(blank=True, upload_to='profile/display')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
    ]
