# Generated by Django 3.0.8 on 2020-11-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crackerbox_', '0002_auto_20201101_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alldocumentcount',
            name='name',
            field=models.CharField(default='Document_count', max_length=50),
        ),
    ]
