# Generated by Django 3.0.8 on 2020-11-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crackerbox_', '0003_auto_20201106_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='unique_id',
            field=models.CharField(default='', max_length=64),
        ),
    ]
