name: CI

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - name: Set up Python 3.7
              uses: actions/setup-python@v1
              with:
                  python-version: 3.7

            # - name: Install dependencies
            #   run: |
            #       python -m pip install --upgrade pip
            #       pip install -r requirements.txt

            - name: executing remote ssh commands using ssh
              uses: appleboy/ssh-action@master
              env:
                  SECRET_KEY: ${{ secrets.SECRET_KEY }}
                  REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
                  EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
                  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.SSH_KEY }}
                  port: ${{ secrets.PORT }}
                  passphrase: ${{ secrets.PASSPHRASE }}
                  envs: SECRET_KEY, REDIS_PASSWORD, EMAIL_HOST_PASSWORD, DB_PASSWORD
                  script: |
                      . .bashrc
                      source miniconda3/etc/profile.d/conda.sh
                      cd StudyQuizzer
                      git pull origin main
                      git reset --hard origin/main
                      conda activate production_env
                      pip install -r requirements.txt
                      python manage.py migrate
